version: '3.8'

services:
  app:
    container_name: cragheads-profile-api
    restart: always
    build: .
    ports:
      - "3015:3015"
    environment:
      - DB_CONN_STRING=mongodb://mongodb:27017/cragheads-db
      - PORT=3015
    volumes:
      - .:/app
    networks:
      - cragheads-profile-network
      - cragheads-shared-network

networks:
  cragheads-profile-network:
    driver: bridge
  cragheads-shared-network:
    external: true